"""create mock_users

Revision ID: a33ebf9b1982
Revises: a6529d500843
Create Date: 2025-11-15 19:21:57.353834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.application.security import SecurityService

# revision identifiers, used by Alembic.
revision: str = 'a33ebf9b1982'
down_revision: Union[str, None] = 'a6529d500843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


service = SecurityService()

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    users_data = [
        ("userone", service.get_password_hash_sync('userone'), "Иван", "Иванов", "Иванович"),
        ("usertwo", service.get_password_hash_sync('usertwo'), "Мария", "Мариева", "Мариевна"),
        ("userthree", service.get_password_hash_sync('userthree'), "Алексей", "Алексеев", None)
    ]
    
    for username, password_hash, first_name, second_name, patronymic in users_data:
        patronymic_value = f"'{patronymic}'" if patronymic else 'NULL'
        op.execute(f"""
            INSERT INTO users (username, hashed_password, first_name, second_name, patronymic)
            VALUES ('{username}', '{password_hash}', '{first_name}', '{second_name}', {patronymic_value})
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM users WHERE username IN ('userone', 'usertwo', 'userthree')")
    # ### end Alembic commands ###
